# .gitlab-ci.yml

# Utilise une image Node.js pour l'environnement de construction
image: node:18-alpine

# Définition des caches pour accélérer les builds futurs
cache:
  paths:
    - node_modules/

# Le pipeline de déploiement pour GitLab Pages
pages:
  stage: deploy
  
  # Les commandes de construction
  script:
    - npm install
    - npm run build
    - rm -rf public
    - mv dist public    # Renomme le dossier de sortie 'dist' en 'public' (requis par GitLab Pages)
  
  # Définition des artefacts : les fichiers qui seront hébergés
  artifacts:
    paths:
      - public
  
  # Condition : s'exécute uniquement sur la branche master
  only:
    - master